#!/env/bin/python

import random

from staff.settings import display_settings
from staff.apple import Apple
from staff.ai_snake import AiSnake



import pygame as pg

def get_random_position(game_object):
    x, y = int(random.randint(0, 8)*80), int(random.randint(0, 8)*80)
    game_object.pos = (x, y)

class Game:
    def __init__(self):
        pg.init()
       self.clock = pg.time.Clock()
        pg.display.set_caption(display_settings.TITLE)
        self.surface = pg.display.set_mode((display_settings.WINDOW_WIDTH, display_settings.WINDOW_HEIGHT))
        self.loop = True
        self.apple = Apple(self.surface)
        self.ai_snake = AiSnake(self.surface)

    def main(self):
        while self.loop:
            self.game_loop()
        pg.quit()

    def game_loop(self):

        self.clock.tick(5)
        self.surface.fill((0, 0, 0))
        for row in range(display_settings.TILES_HORIZONTAL):
            for col in range(row % 2, display_settings.TILES_HORIZONTAL, 2):
                pg.draw.rect(
                    self.surface,
                    (40, 40, 40),
                    (row * display_settings.TILE_SIZE, col * display_settings.TILE_SIZE, display_settings.TILE_SIZE, display_settings.TILE_SIZE),
                )


        self.ai_snake.draw()
        self.apple.draw()
        self.ai_snake.move_towards_apple(self.apple.pos)
        if self.ai_snake.pos == self.apple.pos:
            get_random_position(self.apple)


        # Обработка событий от юзера
        for event in pg.event.get():
            if event.type == pg.QUIT:
                self.loop = False
            elif event.type == pg.KEYDOWN:
                if event.key == pg.K_ESCAPE:
                    self.loop = False
            elif event.type == pg.MOUSEBUTTONUP:
                pos = pg.mouse.get_pos()
                self.apple.move(pos)

        pg.display.update()



mygame = Game()
if __name__ == "__main__":
    mygame.main()
